"use client"
import { Inter } from "next/font/google";
import Appbar from "./component/Appbar/Appbar";
import { usePathname } from "next/navigation"; 
import Footer from "./component/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const pathName = usePathname(); // Correctly use the usePathname hook

  // Correct the conditional checks for rendering Appbar and Footer
  // You need to ensure that the pathname does not equal '/login' or '/signup'
  // The previous condition was not correctly formed and would always evaluate to true due to a misunderstanding of logical operators
  const shouldShowHeaderAndFooter = pathName !== "/login" && pathName !== "/signup";

  return (
    <html lang="en">
      <body className={inter.className}>
        {shouldShowHeaderAndFooter && <Appbar />}
        {children}
        {shouldShowHeaderAndFooter && <Footer />}
      </body>
    </html>
  );
}
